### ISSUE TITLE
Advancement interface: UI and API

### ISSUE THREAD

**Issue by Arcensoth** [TeamEpic/Scripted-Quests#40]
Having the ability to display quest progress in the vanilla advancement UI would be valuable. Not only that, but also being able to interface directly with advancements and their criteria may be a viable alternative to scores. Combining both of these ideas would provide a convenient interface for quest progress by piggy-backing off the vanilla advancement system.

I've used advancements as a consolidated frontend + backend for a pseudo-quest system in vanilla via datapacks, and it worked surprisingly well. This is where the inspiration comes from.

**Dislcaimer:** this is a fairly hefty task, I know, and I'm sure there are dozens upon dozens of more important things on your list. But I figured throwing my ideas down here would be better than keeping them in my head.

Feed back is welcome!

## Advancement UI
This is just to support quest progress as part of the vanilla advancement UI. I assume each quest could become an advancement that's granted after the quest is completed, but more complex cases may be possible depending on how well the quest grammar can be synchronized with advancement criteria.

1. Generate advancements based on quest data. So each quest JSON might turn into one or more advancements/criteria depending on how the display represents quest progress. I don't know plugin dev well enough to say whether this can be done programmatically from the plugin, or if we need to generate and supply the advancements with a separately utility.
2. Decide how to group quests amongst advancements tabs. For example: should all quests go in one tab, which quests should become their own tabs, should the concept of "root quest" be added to the schema in order to control advancement tabs via quest schema, etc.
3. Add quest icons to the schema so these advancements have something to display.

## Advancement API
This would allow a quest definition to interface directly with advancements, for example via prerequisite `check_advancement` and action `grant_advancement`.

1. Add a `check_advancement` case to `QuestPrerequisites` similar to [the existing `check_scores` case](https://github.com/TeamEpic/Scripted-Quests/blob/3840bf1f6277c2f1cce2642cf11090192c6f0d67/plugin/src/main/java/com/playmonumenta/scriptedquests/quests/components/QuestPrerequisites.java#L42).
2. Implement a new `PrerequisiteCheckAdvancement` class likely to be completely different from, but perhaps inspired by, [the existing `PrerequisiteCheckScores`](https://github.com/TeamEpic/Scripted-Quests/blob/3840bf1f6277c2f1cce2642cf11090192c6f0d67/plugin/src/main/java/com/playmonumenta/scriptedquests/quests/components/prerequisites/PrerequisiteCheckScores.java).
3. Add `check_advancement` to [the `prerequisites` schema](https://github.com/TeamEpic/Scripted-Quests/blob/9ac1500cdf34735fc6d8130e86270ea143603f23/tools/schema/prerequisites.json).
4. Add `grant_advancement` to [the `actions` schema](https://github.com/TeamEpic/Scripted-Quests/blob/9ac1500cdf34735fc6d8130e86270ea143603f23/tools/schema/actions.json).
5. Probably some kind of `AdvancementUtils` helper class akin to [the existing `ScoreboardUtils`](https://github.com/TeamEpic/Scripted-Quests/blob/3840bf1f6277c2f1cce2642cf11090192c6f0d67/plugin/src/main/java/com/playmonumenta/scriptedquests/utils/ScoreboardUtils.java) to consolidate common operations on advancements.
6. Possible additions to [`QuestCompassManager`](https://github.com/TeamEpic/Scripted-Quests/blob/4d7358853888e81df477dd96e6f8d606a602b6d5/plugin/src/main/java/com/playmonumenta/scriptedquests/managers/QuestCompassManager.java) to interface with advancements.
7. **Big question:** can advancements be used as a backend to the quest system? If advancements are used to display quest progress, perhaps it's not much of a stretch to also use them for *tracking* quest progress. This would provide a few advantages; namely that quest state won't need to be explicitly managed (checked, set, granted, etc) in the quest definition, greatly reducing the mental overhead involved with writing quests.

**Comment by Combustible** [comment]
Thanks for the ideas! Apologies for the slow response. 

We also use advancements to keep track of quest progress. The main question is - how tightly should we integrate quest progress with advancements?

Today, we use scoreboards to keep track of quest progress. This works, but is obviously not visible to the user. We grant advancements for each quest using either a command action (or a command within a function) upon completion of the quest. Basically we manage advancements from the quest directly, but those advancements are not declared in any way in the quest itself. 

A couple thoughts: 

*** Advancements created by scripted quests ***
I think this is definitely possible - we could for example add some more markup to let you declare your advancement, and then the quest could register it when it loads. 

However - the big risk here is compatibility with future minecraft versions. I got bit by this bad with other plugins I maintain with the 1.13 upgrade. In general I am trying not to integrate too tightly into existing subsystems - I'd prefer you to have to specify advancements separately (via their normal JSON files) and just provide easier ways to get to them here. This gives you maximum flexibility in laying out your quests amongst various tabs/icons/etc. 

*** Advancement API ***
I really like these ideas, and you have a good list. I think we should indeed do all of the 1-5 tasks you list. 

``` 6. Possible additions to QuestCompassManager to interface with advancements.```
Not sure what you have in mind here besides expanding pre-requisites / actions

```
7. Big question: can advancements be used as a backend to the quest system? If advancements are used to display quest progress, perhaps it's not much of a stretch to also use them for tracking quest progress. This would provide a few advantages; namely that quest state won't need to be explicitly managed (checked, set, granted, etc) in the quest definition, greatly reducing the mental overhead involved with writing quests.
```

I think the things you describe above are really the things we should stick to. This would be enough to, as you say, allow the advancements system to be the "back-end" for progress storage instead of scores. This would allow you to check if an advancement has been granted or not and act accordingly - and you can put all of your advancement logic in the advancement file. 

I don't think we should provide an "all-inclusive" place within the scripted quests file for declaring the quest advancements themselves. It would be a lot of work (items 1-5 are quite easy by comparison) and I think sticking with the vanilla advancements declaration process is a good idea.

**Comment by Arcensoth** [comment]
Yeah that is 7 was basically: should quests be *implicitly* handled by advancements? This would provide a convenience in writing quests (because you don't need to explicitly manage advancements in the quest definition) but at the cost of introducing a very tight coupling with the vanilla advancement system. I think you gave good reasoning against this throughout your post.

And 6 was for the sake of completion because I was unsure whether the compass needs to explicitly support advancements. I saw some scoreboard stuff in that class at a glance, but looking again I think it's just being used to manage the active quest. So that point can probably be disregarded.

**Comment by Combustible** [comment]
Oh yeah, good point about the compass. I forgot it uses the scoreboard to track which quest is currently active. I don't think that's really needed - should really move that away from scoreboards and just have it reset when the server restarts instead. Will add a todolist item for that too.

**Comment by Combustible** [comment]
Closing this giant issue in favor of just #44, which tracks the last remaining thing to do (an action to give an advancement to a player easier than using a command action)
